### PR TITLE
Add config option to automatically set the operating system based on `process.platform`

### PR DESCRIPTION
**Pull request by sjkillen**

### CODE REVIEW

**Comment by CaptainUnbrauchbar** [comment]
Thanks for contributing! Actually didn't expect anyone to do stuff here. I actually only created this to be able to run files quickly in VSCode but if you have more ideas feel free to tell me or change stuff! Will release later on.

**Comment by sjkillen** [comment]
No worries, I like it :)
I was getting some errors when I tried to run it on Linux so I thought it'd make a contrib

**Comment by CaptainUnbrauchbar** [comment]
This is actually the first time I'm using Javascript so please don't judge my code ._.
I couldn't test the extension on Mac and Linux yet so please tell me if it runs afterwards!

**Comment by sjkillen** [comment]
Haha, it's all good
I can confirm that it works on Linux. Admittedly, I did not test on Windows.

**Comment by sjkillen** [comment]
As for ideas, I think it would be cool to use an interactive side panel like the Lean VScode extension (https://github.com/leanprover/vscode-lean) rather than the terminal to display information.
The panel could have features like the ability to hide/show predicates without having to rerun the solver or a diff tool to compare differences between answer sets for the same program.

**Comment by CaptainUnbrauchbar** [comment]
Really like the idea of making the output more readable and easier to search/understand with a side panel!
Will take a look into it tomorrow because its almost 4am here, just published your changes btw.

If youre use Discord, you can add me there to make communication easier :)
(Captain Unbrauchbar#8937)

**Pull request merged**
